# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainreplication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63hainreplication.proto\x12\x02\x63r\"c\n\x14\x41ppendEntriesRequest\x12\x0e\n\x06seqnum\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x0e\n\x06\x63lient\x18\x05 \x01(\t\"(\n\x15\x41ppendEntriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\")\n\x0b\x42ucketEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\".\n\x0bSyncRequest\x12\x1f\n\x06\x62ucket\x18\x01 \x03(\x0b\x32\x0f.cr.BucketEntry\"\x1f\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x87\x01\n\x10\x43hainReplication\x12+\n\x04Sync\x12\x0f.cr.SyncRequest\x1a\x10.cr.SyncResponse\"\x00\x12\x46\n\rAppendEntries\x12\x18.cr.AppendEntriesRequest\x1a\x19.cr.AppendEntriesResponse\"\x00\x42&\n\x13io.grpc.examples.crB\x07\x43RProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chainreplication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.examples.crB\007CRProtoP\001\242\002\003HLW'
  _APPENDENTRIESREQUEST._serialized_start=30
  _APPENDENTRIESREQUEST._serialized_end=129
  _APPENDENTRIESRESPONSE._serialized_start=131
  _APPENDENTRIESRESPONSE._serialized_end=171
  _BUCKETENTRY._serialized_start=173
  _BUCKETENTRY._serialized_end=214
  _SYNCREQUEST._serialized_start=216
  _SYNCREQUEST._serialized_end=262
  _SYNCRESPONSE._serialized_start=264
  _SYNCRESPONSE._serialized_end=295
  _CHAINREPLICATION._serialized_start=298
  _CHAINREPLICATION._serialized_end=433
# @@protoc_insertion_point(module_scope)
